### PR TITLE
Act 12

### PR DESCRIPTION
**Pull request by Exilliar**
Added ARC components. Changed the header out to be the one from ARC. I think that there might be some problems with us using both ARC and vuetify, but hopefully they won't be too bad.

Also added routes to the landing and assessments page

Due to the changes to the app.vue page, this might cause some merge conflicts with the other pr's (I think that the login one might get a few), but those also hopefully won't be too bad

### CODE REVIEW

**Comment by Exilliar** [comment]
(this will also require an `npm i` to run cuz ARC components have to be installed

**Comment by psarras** [comment]
@Exilliar do you recommend merging first the login PR then?

**Comment by Exilliar** [comment]
@psarras I think that it might be good to do the login PR first. I can send you guys over the .env file so you cna both test that

**Review by psarras — CHANGES_REQUESTED** [review]
Could you add on the buttons to navigate on the landing / assessment pages?

**Review by psarras — APPROVED** [review]

**Pull request merged**
