### PR TITLE
Custom server

### PR DESCRIPTION
**Pull request by Exilliar**
Adds in the button on the login page to allow users to log into their own speckle servers (currently only works with arup speckle servers). The most recent custom server that the user used will autopopulate the url field and the previous custom servers that they used will be available in the drop down. Both of these are stored in the user's local storage, so if they clear their cache then these will also be cleared, but that should be fine.

I'm not 100% happy with how the modal looks, so happy to make any changes to it.

To test, add in two more vars to the .env file, `VUE_APP_SPECKLE_ID_CUSTOM` and `VUE_APP_SPECKLE_SECRET_CUSTOM` and set these to be the same id and secret as the `VUE_APP_SPECKLE_ID_ARUP` and `VUE_APP_SPECKLE_SECRET_ARUP` fields. Then, in the url field on the custom server modal, enter in the default arup speckle server url (`https://v2.speckle.arup.com`). The login should work and if you log out then the custom server url field should auto fill the default arup speckle server url.

@jenessaman added to pr to test with the hs2 server (if you have time). I can send you a .env file if you do not have one.

I have already updated the github secrets so this should work when deployed

### CODE REVIEW

**Review by ro-sa — COMMENTED** [review]
looks good to me. great job!

Just one question. why does it only work with custom Arup servers? let's discuss tomorrow.

**Comment by Exilliar** [comment]
> looks good to me. great job!
> 
> Just one question. why does it only work with custom Arup servers? let's discuss tomorrow.

cheers.

The quick answer on the Arup servers thing is that in order to allow this feature we need to set up act as a "default app", with a speckle id and secret, on the speckle servers that we want to allow act to log in to. We have been set up as a default app on the main Arup Speckle server (the one that all other Arup Speckle servers are forked from), but have not done that on the main global Speckle server (the one that is run by Speckle Systems and the one that all Speckle servers are forked from).

I'm not 100% on what the process is like for becoming a default app there (or even if it's possible). But it's not a high priority for now (at least this week). So this pr isn't doing that right now, we can try and get it done later.

@jenessaman does this all sound right?

**Comment by Exilliar** [comment]
Made a couple of updates based off feedback from @jenessaman:
1. Fixed a bug where the loading spinner on the landing page would spin forever if the user doesn't have any act reports on the server they're logged in to
2. Added a line in the sidebar saying which server the user is currently logged in to. Not 100% happy with the icon that's being used for it, but it was the best one that I could find

**Review by ro-sa — APPROVED** [review]
looks good. I like the server icon.

**Review by jenessaman — APPROVED** [review]
@Exilliar - thanks for pulling together the change so quickly!

**Pull request merged**
