### PR TITLE
fixed bug

### PR DESCRIPTION
**Pull request by Exilliar**
fixed the bug where the report would not be commited up to Speckle

### CODE REVIEW

**Comment by ro-sa** [comment]
we should add units to the input fields in the transport section. (ideally km, since it's the SI unit)

**Comment by Exilliar** [comment]
> we should add units to the input fields in the transport section. (ideally km, since it's the SI unit)

good idea. I can quickly do that now

**Comment by ro-sa** [comment]
this is a bit picky... when we input the transport data and click the "save" button, could we change it to an "edit" button and grey out the values that the user has put in, so that it's clear that those values have been saved? atm it's a bit confusing if the values are saved on not, since the user get's no queues.

**Comment by Exilliar** [comment]
> this is a bit picky... when we input the transport data and click the "save" button, could we change it to an "edit" button and grey out the values that the user has put in, so that it's clear that those values have been saved? atm it's a bit confusing if whether the values are saved on not, since the user gets no queues.

Good idea! I've updated so that the save button will be disabled once the user has saved the current values. It will re-enable when any of the values change

**Comment by ro-sa** [comment]
there's some vue warning messages in the console about the "speckleStream" property or method. not sure if it's critical, but probably worth looking into.

**Comment by Exilliar** [comment]
> there's some vue warning messages in the console about the "speckleStream" property or method. not sure if it's critical, but probably worth looking into.

Yeah. That's an annoying bug that we're going to have to figure out eventually. It's not affecting the functionality of the page atm though, so was going to leave it for another task. Can do it now if you think I should though

**Comment by ro-sa** [comment]
it would be nice to change the colour or grey out the "SAVE" button in section 7 (Report) to visually inform the user that the report has been saved (similar to the Transport section).

**Comment by Exilliar** [comment]
> it would be nice to change the colour or grey out the "SAVE" button in section 7 (Report) to visually inform the user that the report has been saved (similar to the Transport section).

I think that there's going to need to be some larger UI stuff when saving the report. Probably some form of spinner and then larger message (maybe a popup) saying that the report has been saved. Was going to create an issue for updating the UI for this page, so doing that might fit better into that task than this one?

**Review by ro-sa — APPROVED** [review]
great work!

**Pull request merged**
